ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/Certificate_of_Analysis__c.object-meta.xml
<CustomObject>
    <label>Certificate of Analysis</label>
    <nameField>
        <displayFormat>COA-{0000}</displayFormat>
        <label>B2B COA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates of Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/fields/CAS_Number__c.field-meta.xml
<CustomField>
    <fullName>CAS_Number__c</fullName>
    <label>CAS Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/fields/Characteristics__c.field-meta.xml
<CustomField>
    <fullName>Characteristics__c</fullName>
    <label>Characteristics</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/fields/Display_Date__c.field-meta.xml
<CustomField>
    <fullName>Display_Date__c</fullName>
    <formula>CASE( MONTH(Date__c) , 1, &apos;January&apos;, 2, &apos;February&apos;, 3, &apos;March&apos;, 4, &apos;April&apos;, 5, &apos;May&apos;, 6, &apos;June&apos;, 7, &apos;July&apos;, 8, &apos;August&apos;, 9, &apos;September&apos;, 10, &apos;October&apos;, 11, &apos;November&apos;, &apos;December&apos;) +&apos; &apos;+ TEXT(DAY( Date__c )) +&apos;, &apos;+  TEXT(  YEAR( Date__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>MMMMM DD, YYYY</inlineHelpText>
    <label>Display Date</label>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/fields/Display_Id__c.field-meta.xml
<CustomField>
    <fullName>Display_Id__c</fullName>
    <label>Display Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>B2B_Certificates_of_Authentication1</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/fields/Product_Categories__c.field-meta.xml
<CustomField>
    <fullName>Product_Categories__c</fullName>
    <label>Product Categories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Certificate_of_Analysis__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Product2/fields/Parent_Sku__c.field-meta.xml
<CustomField>
    <fullName>Parent_Sku__c</fullName>
    <label>Parent Sku</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Product2/fields/Unit_Size__c.field-meta.xml
<CustomField>
    <fullName>Unit_Size__c</fullName>
    <label>Unit Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/ProductAttribute/fields/Unit_Size__c.field-meta.xml
<CustomField>
    <fullName>Unit_Size__c</fullName>
    <label>Unit Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>.025mole</fullName>
            </value>
            <value>
                <fullName>.05mole</fullName>
            </value>
            <value>
                <fullName>.25mole</fullName>
            </value>
            <value>
                <fullName>.500mg</fullName>
            </value>
            <value>
                <fullName>0.001mole</fullName>
            </value>
            <value>
                <fullName>0.01mole</fullName>
            </value>
            <value>
                <fullName>0.05mole</fullName>
            </value>
            <value>
                <fullName>0.1mole</fullName>
            </value>
            <value>
                <fullName>0.25mole</fullName>
            </value>
            <value>
                <fullName>0.2mole</fullName>
            </value>
            <value>
                <fullName>0.5mg</fullName>
            </value>
            <value>
                <fullName>0.5ml</fullName>
            </value>
            <value>
                <fullName>0.5mole</fullName>
            </value>
            <value>
                <fullName>1000g</fullName>
            </value>
            <value>
                <fullName>1000m</fullName>
            </value>
            <value>
                <fullName>1000 x 200mm</fullName>
            </value>
            <value>
                <fullName>100cm</fullName>
            </value>
            <value>
                <fullName>100g</fullName>
            </value>
            <value>
                <fullName>100g soln.</fullName>
            </value>
            <value>
                <fullName>100m</fullName>
            </value>
            <value>
                <fullName>100mg</fullName>
            </value>
            <value>
                <fullName>100ml</fullName>
            </value>
            <value>
                <fullName>100mm</fullName>
            </value>
            <value>
                <fullName>100mml</fullName>
            </value>
            <value>
                <fullName>100 x 100mm</fullName>
            </value>
            <value>
                <fullName>100 x 125mm</fullName>
            </value>
            <value>
                <fullName>100 x 200mm</fullName>
            </value>
            <value>
                <fullName>100 x 25mm</fullName>
            </value>
            <value>
                <fullName>100 x 300mm</fullName>
            </value>
            <value>
                <fullName>100 x 30cm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/classes/B2B_ProductDetailCOAService.cls
/**
 * @description       : 
 * @author            : surya.thakur
 * @group             : 
 * @last modified on  : 05-15-2024
 * @last modified by  : surya.thakur
 * test class : B2B_ProductDetailCOAControllerTest
**/
public without sharing class B2B_ProductDetailCOAService {
    public B2B_ProductDetailCOAService() {

    }

    public static Map<String,Object> getCOAData(Map<String,Object> mapParams){
        Boolean isSuccess = false;
        String message = '';
        System.debug('getCOAData mapParams-- '+JSON.serialize(mapParams));
        if( mapParams.containsKey('enteredLotNumber') && ( mapParams.containsKey('productId') || mapParams.containsKey('isPDP') ) ){
            String lotNumInp = (String) mapParams.get('enteredLotNumber');
            String prodIdInp = (String) mapParams.get('productId');
            Boolean isPDPView = (Boolean) mapParams.get('isPDP');
            String catNumInp = (String) mapParams.get('enteredCatNumber');
            if( isPDPView ){
                prodIdInp = getProductData(prodIdInp);
                if( String.isNotBlank(prodIdInp) ){
                    List<Certificate_of_Analysis__c> coaList = returnCOAList(prodIdInp, lotNumInp);
                    List<Certificate_of_Analysis__c> coaListSorted = returnSortedCOAList(prodIdInp, lotNumInp);
                    if( ! coaList.isEmpty() ){
                        mapParams.put('hasData', true);
                        mapParams.put('coaList', coaList);
                        mapParams.put('coaListSorted', coaListSorted);
                    }else{
                        mapParams.put('hasData', false);
                    }
                    isSuccess = true;
                }
            }else{
                List<Certificate_of_Analysis__c> coaList = returnCOAListForNonPDP(catNumInp, lotNumInp);
                List<Certificate_of_Analysis__c> coaListSorted = returnSortedCOAListForNonPDP(catNumInp, lotNumInp);
                if( ! coaList.isEmpty() ){
                    mapParams.put('hasData', true);
                    mapParams.put('coaList', coaList);
                    mapParams.put('coaListSorted', coaListSorted);
                    mapParams.put('productId', coaList[0].Product__c);
                }else{
                    mapParams.put('hasData', false);
                }
                isSuccess = true;
            }
        }
        mapParams.put('isSuccess', isSuccess);
        mapParams.put('message', message);
        return mapParams;
    }

    public static String getProductData(String prodIdInp){
        String prodIdToRetrun;
        List<Product2> prodList = [SELECT Id, ProductClass FROM Product2 WHERE Id =: prodIdInp LIMIT 1];
        if( ! prodList.isEmpty() ){
            Product2 prodObj = prodList[0];
            if( prodObj.ProductClass == 'Variation' ){
                List<ProductAttribute> varChildList = [SELECT Id, Name, ProductId, VariantParentId, Sequence, Unit_Size__c FROM ProductAttribute WHERE ProductId =: prodObj.Id LIMIT 1];
                if( ! varChildList.isEmpty() ){
                    ProductAttribute varChild = varChildList[0];
                    //return variation parent product2 Id
                    prodIdToRetrun = varChild.VariantParentId;
                }
            }else{
                prodIdToRetrun = prodIdInp;
            }
        }
        return prodIdToRetrun;
    }

    public static List<Certificate_of_Analysis__c> returnCOAList(String prodIdInp, String lotNumInp){
        List<Certificate_of_Analysis__c> COAToReturn = new List<Certificate_of_Analysis__c>();
        COAToReturn = [SELECT Id, Name, Lot_Number__c, Specification__c, Result__c, Sequence_Number__c, Catalog_Item_Number__c, Display_Id__c, Characteristics__c, Product_Categories__c, Product_Category__c, CAS_Number__c, Product__c, Product__r.ProductCode, Product__r.Parent_Sku__c, Product_Name__c, Date__c, Display_Date__c FROM Certificate_of_Analysis__c WHERE Product__c =: prodIdInp AND Lot_Number__c =: lotNumInp ORDER BY Sequence_Number__c ];
        return COAToReturn;
    }

    public static List<Certificate_of_Analysis__c> returnCOAListForNonPDP(String catNumInp, String lotNumInp){
        List<Certificate_of_Analysis__c> COAToReturn = new List<Certificate_of_Analysis__c>();
        COAToReturn = [ SELECT Id, Name, Lot_Number__c, Specification__c, Result__c, Sequence_Number__c, Catalog_Item_Number__c, Display_Id__c, Characteristics__c, Product_Categories__c, Product_Category__c, CAS_Number__c, Product__c, Product__r.ProductCode, Product__r.Parent_Sku__c,  Product_Name__c, Date__c, Display_Date__c FROM Certificate_of_Analysis__c WHERE Lot_Number__c =: lotNumInp AND Product__r.Parent_Sku__c = :catNumInp ORDER BY Sequence_Number__c ];
        return COAToReturn;
    }

    public static List<Certificate_of_Analysis__c> returnSortedCOAList(String prodIdInp, String lotNumInp){
        List<Certificate_of_Analysis__c> COAToReturn = new List<Certificate_of_Analysis__c>();
        COAToReturn = [SELECT Id, Name, Lot_Number__c, Specification__c, Result__c, Sequence_Number__c, Catalog_Item_Number__c, Display_Id__c, Characteristics__c, Product_Categories__c, Product_Category__c, CAS_Number__c, Product__c, Product__r.ProductCode, Product__r.Parent_Sku__c, Product_Name__c, Date__c, Display_Date__c FROM Certificate_of_Analysis__c WHERE Product__c =: prodIdInp AND Lot_Number__c =: lotNumInp ORDER BY Date__c DESC];
        return COAToReturn;
    }

    public static List<Certificate_of_Analysis__c> returnSortedCOAListForNonPDP(String catNumInp, String lotNumInp){
        List<Certificate_of_Analysis__c> COAToReturn = new List<Certificate_of_Analysis__c>();
        COAToReturn = [SELECT Id, Name, Lot_Number__c, Specification__c, Result__c, Sequence_Number__c, Catalog_Item_Number__c, Display_Id__c, Characteristics__c, Product_Categories__c, Product_Category__c, CAS_Number__c, Product__c, Product__r.ProductCode, Product__r.Parent_Sku__c, Product_Name__c, Date__c, Display_Date__c FROM Certificate_of_Analysis__c WHERE Product__r.Parent_Sku__c = :catNumInp AND Lot_Number__c =: lotNumInp ORDER BY Date__c DESC];
        return COAToReturn;
    }
    
    public static void testCoverage(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}