ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Cookie__c/fields/CookieConsentCategory__c.field-meta.xml
<CustomField>
    <fullName>CookieConsentCategory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The parent category for the cookie.</description>
    <label>Cookie Consent Category</label>
    <referenceTo>CookieConsentCategory__c</referenceTo>
    <relationshipLabel>Cookies</relationshipLabel>
    <relationshipName>Cookies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Cookie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the cookie</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/CookieConsentCategory__c/fields/AdditionalInformation__c.field-meta.xml
<CustomField>
    <fullName>AdditionalInformation__c</fullName>
    <label>Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/CookieConsentCategory__c/fields/DefaultValue__c.field-meta.xml
<CustomField>
    <fullName>DefaultValue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The default opt-in value for the section.</description>
    <inlineHelpText>The default opt-in value for the section.</inlineHelpText>
    <label>Default Value</label>
    <type>Checkbox</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/CookieConsentCategory__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The category notes that will be displayed to the user viewing the cookie consent modal.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/CookieConsentCategory__c/fields/Manditory__c.field-meta.xml
<CustomField>
    <fullName>Manditory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if the cookie consent section is mandatory.</description>
    <inlineHelpText>Mark true if the section is mandatory</inlineHelpText>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/classes/B2B_CookieConsentTestUtilities.cls
@isTest
public without sharing class B2B_CookieConsentTestUtilities {

	//@future
    public static void createUser(){
        
        Account account = new Account(
                Name = 'testAccount'
        );
        insert account;
        
        Contact contact = new Contact(
                FirstName = 'test',
                LastName = 'contact',
                AccountId = account.Id
        );
        insert contact;

        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'Ascensus Customer Community Plus User' LIMIT 1];
        Profile profile = (profiles.size() == 1) ? profiles.get(0) : null;

        User user = new User(Username = 'test@cookieconsent.com', FirstName = 'First', LastName = 'Last', Email = 'example@example.com', 
                             ProfileId = profile.Id, CompanyName = 'Test', Title ='Title', Alias = 'alias', TimeZoneSidKey = 'America/Los_Angeles', 
                             EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', ContactId = contact.Id, FederationIdentifier = 'CspLitePortal',
                             LocaleSidKey = 'en_US');

        insert user;

        //assignPermissionSet(user);
        
        /*List<PermissionSet> permissionSets = [SELECT Id FROM PermissionSet WHERE Name = 'B2B_Cookie_Consent_Guest_User' LIMIT 1];
        PermissionSet permissionSet = (permissionSets.size() == 1) ? permissionSets.get(0) : null;

        PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment(PermissionSetId = permissionSet.Id, AssigneeId = user.Id);

        insert permissionSetAssignment;*/

    }
    
    @future
    public static void assignPermissionSet( String usrId ){
        List<PermissionSet> permissionSets = [SELECT Id FROM PermissionSet WHERE Name = 'B2B_Commerce_Consent_Management' LIMIT 1];
        PermissionSet permissionSet = (permissionSets.size() == 1) ? permissionSets.get(0) : null;

        PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment(PermissionSetId = permissionSet.Id, AssigneeId = usrId);

        insert permissionSetAssignment;
    }

    @future
    public static void createStandardUser(){

        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'Stack System Administrator' LIMIT 1];
        Profile profile = (profiles.size() == 1) ? profiles.get(0) : null;

        User user = new User(Username = 'standard@cookieconsent.com', FirstName = 'First', LastName = 'Last', Email = 'example@example.com', ProfileId = profile.Id, CompanyName = 'Test', Title ='Title', Alias = 'alias', TimeZoneSidKey = 'America/Los_Angeles', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US');

        insert user;

        List<PermissionSet> permissionSets = [SELECT Id FROM PermissionSet WHERE Name = 'B2B_Cookie_Consent_Guest_User' LIMIT 1];
        PermissionSet permissionSet = (permissionSets.size() == 1) ? permissionSets.get(0) : null;

        PermissionSetAssignment permissionSetAssignment = new PermissionSetAssignment(PermissionSetId = permissionSet.Id, AssigneeId = user.Id);

        insert permissionSetAssignment;

    }

    public static CookieConsentCategory__c createCookieConsentCategory(){

        CookieConsentCategory__c cookieConsentCategory = new CookieConsentCategory__c(Name = 'Test', Description__c = 'Description', DefaultValue__c = true, Manditory__c = true, AdditionalInformation__c = 'Test');

        insert cookieConsentCategory;

        return cookieConsentCategory;

    }

    public static Cookie__c createCookie(Id categoryId){

        Cookie__c cookie = new Cookie__c(Name = 'Test', Description__c = 'Test', CookieConsentCategory__c = categoryId);

        insert cookie;

        return cookie;

    }

    public static Individual createIndividual() {

        Individual newIndividual = new Individual(FirstName = 'Test', LastName = 'Test', BrowserId__c = '123456789');

        insert newIndividual;

        return newIndividual;

    }


}