ASC Prod BAckup/ASC Prod/force-app/main/default/objects/B2B_Google_Merchant_Center__c/B2B_Google_Merchant_Center__c.object-meta.xml
<CustomObject>
    <description>This is used to track GMC conversions for ascensus commerce store.</description>
    <label>B2B Google Merchant Center</label>
    <nameField>
        <displayFormat>GMC-{00000}</displayFormat>
        <label>B2B Google Merchant Center Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2B Google Merchant Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/B2B_Google_Merchant_Center__c/fields/B2B_Contact__c.field-meta.xml
<CustomField>
    <fullName>B2B_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>B2B Google Merchant Centers</relationshipLabel>
    <relationshipName>B2B_Google_Merchant_Centers</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/B2B_Google_Merchant_Center__c/fields/B2B_Key__c.field-meta.xml
<CustomField>
    <fullName>B2B_Key__c</fullName>
    <label>B2B Key</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/B2B_Google_Merchant_Center__c/fields/B2B_Product__c.field-meta.xml
<CustomField>
    <fullName>B2B_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Google Merchant Centers</relationshipLabel>
    <relationshipName>B2B_Google_Merchant_Centers</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/classes/B2B_GoogleTrackingService.cls
/**
* @description       : 
* @author            : Swati Chilap
* @group             : 
* @last modified on  : 25-08-2025
* @last modified by  : Swati Chilap
* @Test Class        : B2B_GoogleTrackingControllerTest
**/
public without sharing class B2B_GoogleTrackingService {

    public static Map<String, Object> createGMCRecord(Map<String, Object> mapParams) {
        Boolean isSuccess = false;
        String message = '';
        Id recordId;

        try {
            System.debug('createGMCRecord mapParams-- ' + JSON.serialize(mapParams));

            String productId = (String) mapParams.get('productId');
            String contactId = (String) mapParams.get('contactId');
            String gmcKey    = (String) mapParams.get('gmcKey');
            Boolean isGuest  = (Boolean) mapParams.get('isGuest');

            B2B_Google_Merchant_Center__c gmc = new B2B_Google_Merchant_Center__c();
            gmc.B2B_Product__c = String.isNotBlank(productId) ? Id.valueOf(productId) : null;
            // only set Contact if not guest
            if(String.isNotBlank(contactId) && ( isGuest == null || isGuest == false)) {
                gmc.B2B_Contact__c = Id.valueOf(contactId);
            }
            gmc.B2B_Key__c = gmcKey;

            insert gmc;
            recordId = gmc.Id;
            isSuccess = true;
            message = 'Record created successfully';
        } catch (Exception e) {
            message = 'Error: ' + e.getMessage();
        }

        mapParams.put('isSuccess', isSuccess);
        mapParams.put('message', message);
        mapParams.put('recordId', recordId);

        return mapParams;
    }
}