ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Industry Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Life Science</fullName>
            </value>
            <value>
                <fullName>Specialties</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Lead_Chemist__c.field-meta.xml
<CustomField>
    <fullName>Lead_Chemist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RD Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RD_Portfolio2</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DSBH</fullName>
            </value>
            <value>
                <fullName>LSBH</fullName>
            </value>
            <value>
                <fullName>TMB</fullName>
            </value>
            <value>
                <fullName>Caustic</fullName>
            </value>
            <value>
                <fullName>Boranes</fullName>
            </value>
            <value>
                <fullName>Alcoholates</fullName>
            </value>
            <value>
                <fullName>Alkali Metals</fullName>
            </value>
            <value>
                <fullName>Catalog</fullName>
            </value>
            <value>
                <fullName>GMP</fullName>
            </value>
            <value>
                <fullName>Intermediates</fullName>
            </value>
            <value>
                <fullName>TFD/CVD</fullName>
            </value>
            <value>
                <fullName>TMBa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/RD_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>RD_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RD Portfolio</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/recordTypes/R_D_Portfolio.recordType-meta.xml
<RecordType>
    <fullName>R_D_Portfolio</fullName>
    <active>true</active>
    <businessProcess>R %26 D Portfolio</businessProcess>
    <label>R &amp; D Portfolio</label>
</RecordType>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/RD_Portfolio__c.object-meta.xml
<CustomObject>
    <description>This is a RD Portfolio Custom Object</description>
    <label>RD Portfolio (OLD)</label>
    <nameField>
        <label>RD Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RD Portfolios (OLD)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/fields/Lead_Chemist__c.field-meta.xml
<CustomField>
    <fullName>Lead_Chemist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Chemist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RD_Portfolio</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/fields/Open_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Open_Milestone__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Open Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/fields/Project_NPV__c.field-meta.xml
<CustomField>
    <fullName>Project_NPV__c</fullName>
    <description>NPV of the project</description>
    <label>Project NPV ($M)</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/classes/TaskTriggerTest.cls
/**
 * @description Test class for Task Trigger.
 * @Author Atrium - Nipun Jain
 * @date Nov 2024
 */

@isTest
public class TaskTriggerTest {

    @isTest
    /**
     * @description Test method to test the task trigger.
     */
    public static void testMethodFirst() {
        User u = createUser(
            'systemAdmin@asc.com.test', 
            'System Admin', 
            [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id
        );
        insert u;

        System.runAs(u) {
            
            Account acc = new Account(Name = 'Test Account');
            insert acc;
            
            Id oppPortfolioRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('R_D_Portfolio').getRecordTypeId();
            Opportunity opp = new Opportunity();
            opp.Name = 'Test Opportunity';
            opp.StageName = 'Stage 0 - Idea';
            opp.Project_Status__c = 'Active';
            opp.AccountId = acc.Id;
            opp.CloseDate = Date.Today().addDays(10);
            opp.Product_Family__c = 'DSBH';
            opp.Industry_Segment__c = 'Life Science';
            opp.Probability = 30;
            opp.Project_NPV__c = 100;
            opp.RecordTypeId = oppPortfolioRecordTypeId;
            insert opp;
            
            List<RD_Portfolio__c> portfolios = new List<RD_Portfolio__c>();

            RD_Portfolio__c folio = new RD_Portfolio__c();
            folio.Name = 'test project';
            folio.Lead_Chemist__c = u.Id;
            folio.Project_NPV__c = 100;
            portfolios.add(folio);
            insert portfolios;

            List<Task> tasks = new List<Task>();
            Task firstTask = new Task();
            firstTask.Subject = 'Call';
            firstTask.OwnerId = u.Id;
            firstTask.ActivityDate = System.today().addDays(1);
            firstTask.Priority = 'Normal';
            firstTask.Status = 'Open';
            firstTask.WhatId = portfolios[0].Id;
            tasks.add(firstTask);

            Task secondTask = new Task();
            secondTask.Subject = 'Call';
            secondTask.OwnerId = u.Id;
            secondTask.ActivityDate = System.today().addDays(1);
            secondTask.Priority = 'Normal';
            secondTask.Status = 'Completed';
            secondTask.WhatId = portfolios[0].Id;
            tasks.add(secondTask);
            
            Task thirdTask = new Task();
            thirdTask.Subject = 'Call Opp';
            thirdTask.OwnerId = u.Id;
            thirdTask.ActivityDate = System.today().addDays(1);
            thirdTask.Priority = 'Normal';
            thirdTask.Status = 'Open';
            thirdTask.WhatId = opp.Id;
            tasks.add(thirdTask);

            insert tasks;

            RD_Portfolio__c portfolio = [SELECT Id, Open_Milestone__c FROM RD_Portfolio__c WHERE Name = 'test project' LIMIT 1];
            System.assertEquals(1, portfolio.Open_Milestone__c, 'Open Milestone count should be 1');

            tasks[0].status = 'Completed';
            tasks[1].status = 'Open';
            update tasks;

            delete tasks;
        }

    }

    private static User createUser(String userName, String lastName, Id profileId) {
        User targetUser = new User();
        targetUser.Username = userName;
        targetUser.Email = userName;
        targetUser.LastName = lastName;
        targetUser.Alias = lastName.left(8);
        targetUser.TimeZoneSidKey = 'America/New_York';
        targetUser.LocaleSidKey = 'en_US';
        targetUser.LanguageLocaleKey = 'en_US';
        targetUser.EmailEncodingKey = 'ISO-8859-1';
        targetUser.ProfileId = profileId;

        return targetUser;
    }

}