ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Lead/recordTypes/Ascensus.recordType-meta.xml
<RecordType>
    <fullName>Ascensus</fullName>
    <active>true</active>
    <businessProcess>Master Lead Process</businessProcess>
    <label>Ascensus</label>
</RecordType>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Industry Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Life Science</fullName>
            </value>
            <value>
                <fullName>Specialties</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Lead_Chemist__c.field-meta.xml
<CustomField>
    <fullName>Lead_Chemist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RD Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RD_Portfolio2</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DSBH</fullName>
            </value>
            <value>
                <fullName>LSBH</fullName>
            </value>
            <value>
                <fullName>TMB</fullName>
            </value>
            <value>
                <fullName>Caustic</fullName>
            </value>
            <value>
                <fullName>Boranes</fullName>
            </value>
            <value>
                <fullName>Alcoholates</fullName>
            </value>
            <value>
                <fullName>Alkali Metals</fullName>
            </value>
            <value>
                <fullName>Catalog</fullName>
            </value>
            <value>
                <fullName>GMP</fullName>
            </value>
            <value>
                <fullName>Intermediates</fullName>
            </value>
            <value>
                <fullName>TFD/CVD</fullName>
            </value>
            <value>
                <fullName>TMBa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/recordTypes/R_D_Portfolio.recordType-meta.xml
<RecordType>
    <fullName>R_D_Portfolio</fullName>
    <active>true</active>
    <businessProcess>R %26 D Portfolio</businessProcess>
    <label>R &amp; D Portfolio</label>
</RecordType>

ASC Prod BAckup/ASC Prod/force-app/main/default/classes/OpportunityTriggerTest.cls
/**-----------------------------------------------------------------------------------------------------
* @description Opportunity Trigger Test
 * @Author Atrium - nipun.jain@atrium.ai
 * @date Feb 2025
------------------------------------------------------------------------------------------------------**/
@isTest
public class OpportunityTriggerTest {

    @isTest
    public static void triggerTestingMethod() {
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User leadChemist = createUser('leadChemist@ascensus.com', 'Assigned Lead Chemist', pf.Id);
        insert leadChemist;
        
        User updatedLeadChemist = createUser('updatedLeadChemist@ascensus.com', 'Updated Lead Chemist', pf.Id);
        insert updatedLeadChemist;

        User testingUser = createUser('testingUser@ascensus.com', 'Testing User', pf.Id);
        insert testingUser;
        
        System.runAs(testingUser) {
            Account acc = new Account(Name = 'Test Account');
            insert acc;
            
            Id oppPortfolioRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('R_D_Portfolio').getRecordTypeId();
            Opportunity opp = new Opportunity();
            opp.Name = 'Test Opportunity';
            opp.StageName = 'Stage 0 - Idea';
            opp.Project_Status__c = 'Active';
            opp.AccountId = acc.Id;
            opp.CloseDate = Date.Today().addDays(10);
            opp.Product_Family__c = 'DSBH';
            opp.Industry_Segment__c = 'Life Science';
            opp.Probability = 30;
            opp.Project_NPV__c = 100;
            opp.RecordTypeId = oppPortfolioRecordTypeId;
            opp.Lead_Chemist__c = leadChemist.Id;
            insert opp;

            string manualSharing = Schema.OpportunityShare.RowCause.Manual;
            List<OpportunityShare> opportunityShares = [SELECT Id, UserOrGroupId, OpportunityId
                                                        FROM OpportunityShare
                                                        WHERE
                                                        OpportunityId =: opp.Id AND
                                                        RowCause =: manualSharing AND
                                                        UserOrGroupId =: leadChemist.Id];
            System.assertEquals(1, opportunityShares.size(), 'Lead Chemist should have access to the Opportuntity');
            opp.Lead_Chemist__c = updatedLeadChemist.Id;
            update opp;
        }
    }
    
    private static User createUser(String userName, String lastName, Id profileId) {
        User targetUser = new User();
        targetUser.Username = userName;
        targetUser.Email = userName;
        targetUser.LastName = lastName;
        targetUser.Alias = lastName.left(8);
        targetUser.TimeZoneSidKey = 'America/New_York';
        targetUser.LocaleSidKey = 'en_US';
        targetUser.LanguageLocaleKey = 'en_US';
        targetUser.EmailEncodingKey = 'ISO-8859-1';
        targetUser.ProfileId = profileId;

        return targetUser;
    }

}