ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Lead/recordTypes/Ascensus.recordType-meta.xml
<RecordType>
    <fullName>Ascensus</fullName>
    <active>true</active>
    <businessProcess>Master Lead Process</businessProcess>
    <label>Ascensus</label>
</RecordType>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Industry_Segment__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment__c</fullName>
    <label>Industry Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Life Science</fullName>
            </value>
            <value>
                <fullName>Specialties</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <default>true</default>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Lead_Chemist__c.field-meta.xml
<CustomField>
    <fullName>Lead_Chemist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RD Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RD_Portfolio2</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Original_RD_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Original_RD_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original RD Portfolio</label>
    <referenceTo>RD_Portfolio__c</referenceTo>
    <relationshipLabel>Opportunities (Original RD Portfolio)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DSBH</fullName>
            </value>
            <value>
                <fullName>LSBH</fullName>
            </value>
            <value>
                <fullName>TMB</fullName>
            </value>
            <value>
                <fullName>Caustic</fullName>
            </value>
            <value>
                <fullName>Boranes</fullName>
            </value>
            <value>
                <fullName>Alcoholates</fullName>
            </value>
            <value>
                <fullName>Alkali Metals</fullName>
            </value>
            <value>
                <fullName>Catalog</fullName>
            </value>
            <value>
                <fullName>GMP</fullName>
            </value>
            <value>
                <fullName>Intermediates</fullName>
            </value>
            <value>
                <fullName>TFD/CVD</fullName>
            </value>
            <value>
                <fullName>TMBa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/fields/RD_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>RD_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RD Portfolio</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/Opportunity/recordTypes/R_D_Portfolio.recordType-meta.xml
<RecordType>
    <fullName>R_D_Portfolio</fullName>
    <active>true</active>
    <businessProcess>R %26 D Portfolio</businessProcess>
    <label>R &amp; D Portfolio</label>
</RecordType>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/RD_Portfolio__c.object-meta.xml
<CustomObject>
    <description>This is a RD Portfolio Custom Object</description>
    <label>RD Portfolio (OLD)</label>
    <nameField>
        <label>RD Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RD Portfolios (OLD)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/fields/Lead_Chemist__c.field-meta.xml
<CustomField>
    <fullName>Lead_Chemist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Chemist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RD_Portfolio</relationshipName>
    <type>Lookup</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/fields/Project_NPV__c.field-meta.xml
<CustomField>
    <fullName>Project_NPV__c</fullName>
    <description>NPV of the project</description>
    <label>Project NPV ($M)</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/objects/RD_Portfolio__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ASC Prod BAckup/ASC Prod/force-app/main/default/classes/ATR_oldRDPortfolioWarningBannerContTest.cls
/**
 * @description     Test class for ATR_oldRDPortfolioWarningBannerCont.
 *                  Validates the logic for fetching an Opportunity related to a given RD Portfolio.
 * @author          nipun.jain@atrium.ai
 * @since           April 2025
 */
@isTest
public class ATR_oldRDPortfolioWarningBannerContTest {

    /**
     * @description     Sets up test data including users, RD Portfolio, Account, and Opportunity 
     *                  for use in test methods.
     */
    @testSetup
    public static void setupMethod() {
        Profile pf = [Select Id from Profile where Name = 'Ascensus Standard User - Minimum Access'];
        User testingUser = createUser('testingUser@ascensus.com', 'Testing User', pf.Id);
        insert testingUser;
        
        PermissionSetGroup psGroup = [SELECT Id FROM PermissionSetGroup WHERE DeveloperName = 'Ascensus_Standard_User_PSG' LIMIT 1];
        
        Test.calculatePermissionSetGroup(psGroup.Id);
        
        PermissionSetAssignment psgAssignment = new PermissionSetAssignment();
        psgAssignment.AssigneeId = testingUser.Id;
        psgAssignment.PermissionSetGroupId = psGroup.Id;
        insert psgAssignment;

        List<PermissionSet> psList = [SELECT Id FROM PermissionSet WHERE Name IN ('Legacy_R_D_Portfolio_Read_Access')];
        List<PermissionSetAssignment> psaList = new List<PermissionSetAssignment>();

        for (PermissionSet ps: psList) {
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.AssigneeId = testingUser.Id;
            psa.PermissionSetId = ps.Id;
            psaList.add(psa);
        }

        insert psaList;

        // PermissionSet legacyRdPortfolioPS = [SELECT Id FROM PermissionSet WHERE Name = 'Legacy_R_D_Portfolio_Read_Access' LIMIT 1];
        // PermissionSetAssignment psa1 = new PermissionSetAssignment();
        // psa1.AssigneeId = testingUser.Id;
        // psa1.PermissionSetId = legacyRdPortfolioPS.Id;
        // insert psa1;
        
        User leadChemist = createUser('leadChemist@ascensus.com', 'Assigned Lead Chemist', pf.Id);
        insert leadChemist;
                
        System.runAs(testingUser) {
            RD_Portfolio__c portfolio = new RD_Portfolio__c();
            portfolio.Name = 'test project';
            portfolio.Lead_Chemist__c = leadChemist.Id;
            insert portfolio;

            Account acc = new Account(Name = 'Test Account');
            insert acc;
            
            Id oppPortfolioRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('R_D_Portfolio').getRecordTypeId();
            Opportunity opp = new Opportunity();
            opp.Name = 'Test Opportunity';
            opp.StageName = 'Stage 0 - Idea';
            opp.Project_Status__c = 'Active';
            opp.AccountId = acc.Id;
            opp.CloseDate = Date.Today().addDays(10);
            opp.Product_Family__c = 'DSBH';
            opp.Industry_Segment__c = 'Life Science';
            opp.Probability = 30;
            opp.Project_NPV__c = 100;
            opp.RecordTypeId = oppPortfolioRecordTypeId;
            opp.Lead_Chemist__c = leadChemist.Id;
            opp.Original_RD_Portfolio__c = portfolio.Id;
            insert opp;
        }
    }
    
    /**
     * @description     Tests the getChildOpportunity method to ensure the correct Opportunity 
     *                  is returned for the given RD Portfolio.
     */
    @isTest
    public static void testController() {
        User user = [SELECT Id FROM User WHERE UserName = 'testingUser@ascensus.com' LIMIT 1];
        RD_Portfolio__c portfolio = [SELECT Id FROM RD_Portfolio__c WHERE Name = 'test project' LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        System.runAs(user) {
            Opportunity returnedOpp = ATR_oldRDPortfolioWarningBannerCont.getChildOpportunity(portfolio.Id);
            System.assertEquals(returnedOpp.Id, opp.Id, 'Opportunity Id not matching.');
        }
    }
    
    /**
     * @description     Helper method to create a User with provided details.
     * @param           userName   The username (also used for email) of the User.
     * @param           lastName   The last name (and alias base) of the User.
     * @param           profileId  The Profile Id to assign to the User.
     * @return          User       The constructed User instance (not inserted).
     */
    private static User createUser(String userName, String lastName, Id profileId) {
        User targetUser = new User();
        targetUser.Username = userName;
        targetUser.Email = userName;
        targetUser.LastName = lastName;
        targetUser.Alias = lastName.left(8);
        targetUser.TimeZoneSidKey = 'America/New_York';
        targetUser.LocaleSidKey = 'en_US';
        targetUser.LanguageLocaleKey = 'en_US';
        targetUser.EmailEncodingKey = 'ISO-8859-1';
        targetUser.ProfileId = profileId;

        return targetUser;
    }

}